### ISSUE TITLE
是需要我在当前一个 vitePress 项目中，加入这个 feishu-page 么

### ISSUE THREAD

**Issue by NasaRocket** [longbridgeapp/feishu-pages#3]
![image](https://github.com/longbridgeapp/feishu-pages/assets/38005687/ab429b16-e3f2-4677-b1cf-96aeba5441f0)
按照步骤，是需要在一个项目中加入这个包，如果这个项目是 vitePress 的项目是不是就可以生成 vitePress 的文档

**Comment by huacnlee** [comment]
你试试就知道了，是这样的

**Comment by NasaRocket** [comment]
> 你试试就知道了，是这样的

您好，方便加一个飞书联系方式交流一下么
Xuqi Fang申请添加你为联系人，点击链接处理 https://www.feishu.cn/invitation/page/add_contact/?token=718oa76b-408b-4067-89e9-ab4c88dc3f17&amp;unique_id=_77gP_KlTagtSYna513R_Q==

**Comment by huacnlee** [comment]
有问题的话，这里提具体问题，我会回答的并改进指导文档，这样其他类似的问题有参考。

**Comment by NasaRocket** [comment]
> 有问题的话，这里提具体问题，我会回答的并改进指导文档，这样其他类似的问题有参考。

好的，我根据我当前的情况咨询一下，目前我在本地初始化好的一个 vitePress 项目中，成功运行，并在 dist 目录下生成了 docs.json 以及 docs 文件夹，根据您给的 example-website 中的内容，如果我想将 dist 中的内容用于网站展示，是否需要以下步骤：
1. 将 dist 中的内容复制出来
2. 将 config.mts 中，读取 docs.json 转化为 sidebar 的逻辑复制一份
这样就可以将生成的doc内容使用起来，后续如果需要维护，则主要是维护 config.mts 中的内容
不知道我这样的理解是否正确

**Comment by huacnlee** [comment]
对的，就是这样的
