### ISSUE TITLE
支持飞书国际版吗？

### ISSUE THREAD

**Issue by shenweiyan** [longbridgeapp/feishu-pages#4]
如题，飞书国际版 https://www.larksuite.com/

**Comment by huacnlee** [comment]
试试 我感觉支持，飞书应该不至于两套 API

**Comment by shenweiyan** [comment]
> 你试试 我感觉支持，飞书应该不至于两套 API

切换为飞书国际版，API 地址应该要调整成 https://open.larksuite.com/，源码中有哪些地方是需要修改的呢？

**Comment by huacnlee** [comment]
可以了

**Comment by shenweiyan** [comment]
试了一下，飞书国际版也可以正常使用了，再次感谢作者优秀的项目！
