### ISSUE TITLE
您好，我在测试导出时遇到两个问题：图片404的时候，会导出报错跳出；导出带有额外的html编码；

### ISSUE THREAD

**Issue by profoundeye** [longbridgeapp/feishu-pages#5]
图片404的时候，会导出报错跳出；
<img width="1645" alt="image" src="https://github.com/longbridgeapp/feishu-pages/assets/781629/38a205a3-68ac-4cda-b16d-4846c2048080">

导出带有额外的html编码；
![img_v2_a3ae1385-8ef7-41b5-b177-46b2da179b2g](https://github.com/longbridgeapp/feishu-pages/assets/781629/6f1fb250-17a0-4c6b-8f4e-a99ea264e046)

**Comment by huacnlee** [comment]
Grid 这个问题我昨天应该修了的，你试试最新的 feishu-pages NPM，新的方式 Grid 内部会生成 HTML

**Comment by huacnlee** [comment]
https://longbridgeapp.github.io/feishu-pages/zh-CN/feishu-docx

我写了一篇文档，介绍这些特殊的内容格式。
