### ISSUE TITLE
分栏column比例没有实现

### ISSUE THREAD

**Issue by shitou333111** [longbridgeapp/feishu-pages#7]
非常棒的工具！
飞书等云笔记相较md一个优势是有分栏等布局。当前实现了分栏，但没有考虑分栏的比例，都是按照平分的布局，比如两栏55分。看到代码中是有这个变量的，只是没有处理。
https://github.com/longbridgeapp/feishu-pages/blob/bdf385fd616c54f3d7b07cd55e62ecce8c65dee3/feishu-docx/src/types.ts#L449

可以加上这个处理吗？因为分栏还是挺重要的一个功能，否则整个文档布局会乱掉。

**Comment by huacnlee** [comment]
我看看

**Comment by huacnlee** [comment]
https://github.com/longbridgeapp/feishu-pages/releases/tag/v0.6.5
